### ISSUE TITLE
Accessing by Linux

### ISSUE THREAD

**Issue by yurimatheus** [dynamsoftsamples/nodejs-dwt#4]
I develop using Ubuntu as my operating system and realized it is giving error when I try to run the file: "server.js"

app.use (express.static (__ dirname, '/ public'));

... I change the public directory for documents ( '/Documentos') and gave the following error:

/home/user/Documentos/projeto/node_modules/serve-static/index.js:47
   var opts = Object.create (options || null)

What can I do? Or rather what I'm doing wrong?

**Comment by yushulx** [comment]
The issues is caused by express version. I guess you are using the latest express. After I upgraded my express module, I got the same problem. To fix it, you just need to change ',' to '+'. Here is the latest  code:

```
app.use(express.static(__dirname)); 
app.use(express.static(__dirname + '/Resources')); 
```
